### ISSUE TITLE
[BUG] The dataframes of Results-acquisitions get the concatenation indexes wrong

### ISSUE THREAD

**Issue by GuillermoAbadLopez** [qilimanjaro-tech/qililab#436]
### Expected behavior & Actual behavior

The concatenation index is just a copy of the final index after the concatenation (a unique index from 0 to X, where X is the number of rows of the final df) instead than what is stated in the docstring (a not unique index that tells your from which element of the concatenated list that row comes from):
<img width="1079" alt="Screenshot 2023-08-08 at 13 49 44" src="https://github.com/qilimanjaro-tech/qililab/assets/109400222/8a2ba461-b3fc-436d-98d8-5097dcd2f52e">

Also I think that the way the loop index and final index Javier added automatically takes into account the behavior of that in the wrong way. 

(But I have to check it might be that everything is working correctly and only the docstring was wrong, check again in the future)

### Additional information

I had actually solved this in this PR: https://github.com/qilimanjaro-tech/qililab/pull/414 

But since the PR become stopped, I never tested/pursued the solution further. And now I am worried that we forget about it.

(In that PR that is already solved, but still many things left to do, maybe split it in two, and merge the first part with the bug solved)

### Existing GitHub issues

- [ ] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by AlbertMitjans** [comment]
We are moving away from the `acquisitions` method. 

We should encourage users to use `results.array`, `results.samples()`, `results.counts()` and `results.acquisitions()`.

I am therefore closing this issue.
