### ISSUE TITLE
[BUG] Performing measurements, sometimes skip Loops elements

### ISSUE THREAD

**Issue by GuillermoAbadLopez** [qilimanjaro-tech/qililab#492]
### Description

Conversation to discover bug:

- Hi! I’ve noticed that while performing measurements sometimes qililab seems to skip some points. For example I was doing an experiment with two nested loops, one of 51 points and the other of 11, so I was expecting to get as a result 1122 points (taking into account both i and q). However I just got 1120. Any idea about what can be happening? With the same loops just changing the hardware average value the problem dissapears

+ That's weird, but since it is only skipping 1 point (i,q) the first I would think is that what is missing is the first (i,q) or the last (i,q) 

- Yes, it’s just missing one point, but I don’t understand why depending on the hardware average I use it happens or not 

+ Maybe its just the typicall missing a print/return before entering the loop or something similar.
If you do a non-nested loop (only one loop), is it also missing that one point? Can you please print the length of the loops you are using? You can do so with: `print(len(loop.values))`

- Now it’s been 2 points
![Captura de pantalla 2023-08-04 a les 14 49 02](https://github.com/qilimanjaro-tech/qililab/assets/109400222/ce247662-fe2a-423d-9c33-c8f9871baf83)

![Captura de pantalla 2023-08-04 a les 14 26 55](https://github.com/qilimanjaro-tech/qililab/assets/109400222/486d79ee-9297-4b25-a2ad-790a4e61152f)

+ Thanks! Is it the exact same experiment, printing now one less even?

- Yes! Exactly the same parameters

 + Can you share the code? Next week someone from the team should try to replicate this bug with the instruments at Meraki such that we can fix it (edited) 

### Additional information

I'll imporve the bug description and add code on monday!

### Source code

Hola! L’experiment que estava fent és aquest:
https://github.com/qilimanjaro-tech/HardwareDataTools/blob/bsc-working/src/hwdatatools/experiment_portfolio/two_tone.py

Amb aquest notebook:
https://github.com/qilimanjaro-tech/LabScripts/blob/main/QuantumPainHackathon/run_qubit_spectroscopy.ipynb

Però no crec que sigui només d’aquest experiment perquè m’he trobat el mateix problema fent altres coses. I comentant-ho amb el Ramiro a ell també li havia passat

### Existing GitHub issues

- [ ] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by AlbertMitjans** [comment]
Hi Guille, given that the `Experiment` class is deprecated and will be removed soon, I will close this issue.
