### ISSUE TITLE
[BUG] system_control.compile() should not try to compile when S4g is in the bus

### ISSUE THREAD

**Issue by paulqili** [qilimanjaro-tech/qililab#556]
### Expected behavior

`system_control.compile()` should skip non AWG type instruments

### Actual behavior

`system_control.compile()` tries to compile for all instruments in the bus, now we use S4g instruments in the bus which are not instances of `AWG` and we get an `AttributeError`

See image:

<img width="1459" alt="image" src="https://github.com/qilimanjaro-tech/qililab/assets/113030828/e14967c0-91e0-4b39-9dfa-d928af7488b1">

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by jjmartinezQT** [comment]
This has been fixed and merged into main.
