### ISSUE TITLE
[BUG] Decimals are losing precision when dumped with yaml.dump()

### ISSUE THREAD

**Issue by GuillermoAbadLopez** [qilimanjaro-tech/qililab#579]
### Expected behavior

Decimals should conserve all the precision

### Actual behavior

They stay on 6 digits precission

### Additional information

Found its due to the `yaml_representer`, concretely this line is killing the recession:
![image](https://github.com/qilimanjaro-tech/qililab/assets/109400222/12c3ebbc-0fb2-4bea-b24c-fb07f7094399)
This was created to work with scientific notation

The normal `yaml.dump()` cannot work with big decimals either

Since `ruamel.yaml.YAML().dump`  can work both with long decimals and scientific notations, we thought its a good solution to tackle it using it.

**Comment by AlbertMitjans** [comment]
Please close the issue if this was fixed.
