### ISSUE TITLE
[BUG] `Asserts` inside `with` are not really asserting anything in qililab tests.

### ISSUE THREAD

**Issue by GuillermoAbadLopez** [qilimanjaro-tech/qililab#582]
### Expected behavior

We should assert things during tests.

### Actual behavior

Asserts inside `with`, never make a test fail! 
![Screenshot 2023-10-26 at 16 01 54](https://github.com/qilimanjaro-tech/qililab/assets/109400222/34b10ef5-e989-4f28-aae5-e02dfa0fe96d)

**Comment by GuillermoAbadLopez** [comment]
What acuatlly is happening :

The error makes you leave the with, so the assert is never actually run
(I just debugged this, and its true, you never arrive to the assert, since the erro makes you leave the with)

**Comment by AlbertMitjans** [comment]
To be more precise, this only happens when using `with pytest.raises`.

**Comment by GuillermoAbadLopez** [comment]
There was only one test doing this incorrectly in the end, and has been changed! 
Clossing the Issue 👍
