### ISSUE TITLE
[BUG] Qblox controller clear cache not working as intended

### ISSUE THREAD

**Issue by visagim** [qilimanjaro-tech/qililab#584]
### Expected behavior

Qblox' `clear_cache` should run the qblox command `cluster.clear` which clears the cluster's cache

### Actual behavior

clear cache in qililab runs
```python
    @QbloxController.CheckConnected
    def reset(self):
        """Reset instrument."""
        self.device.reset()
        for module in self.modules:
            module.clear_cache()
```

which does for each module
```python
    def clear_cache(self):
        """Empty cache."""
        self._cache = {}
        self.sequences = {}
```
where `_cache` is defined at `__init__` as
```python
    _cache: dict[int, PulseBusSchedule] = {}
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by jjmartinezQT** [comment]
This is not a bug and it is working as intended. Clearing the cache is an internal software procedure not related to the clearing of the physical cache, which is achieved by resetting the instrument.
