### ISSUE TITLE
[QHC-43] [BUG] Qblox module markers value hardcoded to 15 (RF-modules are the most affected)

### ISSUE THREAD

**Issue by 4dri8** [qilimanjaro-tech/qililab#629]
### Expected behavior

The marker value should be set to 0 if no output of the module is being used, 1 if only the O0 is being used, 2 if only the O1 is being used, or 2 if both O0 and O1 are being used, and after measuring, set to 0 again so we only send the actual gates. This depends on the circuit you are going to measure, and should be set at the Q1ASM program sent to the used sequencer.

### Actual behavior

This marker value is hardcoded at 15 when executing the `platform.initial_setup()`, this opens all outputs in all modules even if you are just using one output of one module, this leads to all the other modules sending a signal at the given LO frequency, and so increasing noise or in some situations exciting other qubits.

### Additional information

It is easy to reproduce, just take a module and send something in one output and read on the other one with a spectrum analyzer for example, you will notice that the given gate is executed and then there's a signal that still there even if the measurement has ended.

### System Information

```Shell
Name: qililab
Version: 0.20.4
Summary: Fundamental package for fast characterization and calibration of quantum chips.
Home-page: https://github.com/qilimanjaro-tech/qililab
Author: Qilimanjaro Quantum Tech
Author-email: info@qilimanjaro.tech
License: Apache License 2.0
Location: /home/anavarro/miniconda3/envs/qililab-main/lib/python3.10/site-packages
Editable project location: /home/anavarro/qililab
Requires: h5py, lmfit, pandas, PyVISA-py, PyYAML, qblox-instruments, qcodes, qcodes-contrib-drivers, qibo, qiboconnection, qpysequence, rustworkx, tqdm, urllib3
Required-by: 

Platform info:             Linux-5.15.0-86-generic-x86_64-with-glibc2.35
Python version:            3.10.11
PyVISA version:            0.5.2
QCodes version:            0.38.1
QCodes Contrib version:    0.18.0
Qblox Instrument version:  0.10.1
Qpysequence version:       0.9.3
Quantum Machines version:  1.1.3
Qibo version:              0.1.12.dev0
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

<sub>[QHC-43](https://linear.app/qilimanjaro/issue/QHC-43/[bug]-qblox-module-markers-value-hardcoded-to-15-rf-modules-are-the)</sub>

**Comment by jjmartinezQT** [comment]
This has been fixed now.
