### ISSUE TITLE
[BUG] Qblox rf module crashes on `get_parameter`

### ISSUE THREAD

**Issue by visagim** [qilimanjaro-tech/qililab#639]
### Expected behavior

In qblox non-rf modules you can ask for a parameter in a module like `IF = platform.get_parameter(alias=f"drive_q{QUBIT}_bus", parameter=ql.Parameter.IF)`

### Actual behavior

For rf modules this doesnt work and you have to give the channel id i.e.
`IF = platform.get_parameter(alias=f"drive_q{QUBIT}_bus", parameter=ql.Parameter.IF, channel_id=QUBIT)`

### Additional information

@paulqili raised this issue

### System Information

@paulqili raised this issue, ask him for his config

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by jjmartinezQT** [comment]
This one was fixed and included in release 0.22.1
