### ISSUE TITLE
Add threshold to qblox_measurement_result.py in QProgram

### ISSUE THREAD

**Issue by 4dri8** [qilimanjaro-tech/qililab#704]
### Feature details

I would like the possibility to get the thresholded acquisitions other than the IQ array, just like Qililab does.

### Implementation

This idea is already working, not sure if it is well written and general.
In the `measurement_result.py` the next property should be added:

```python
    @property
    @abstractmethod
    def threshold(self) -> np.ndarray:
        """Returns the thresholded data for the result.

        Returns:
            np.ndarray: Thresholded data for the result.
        """
``` 

And in `qblox_measurement_result.py` this property which returns the thresholded bins from the raw results:

```python
    @property
    def threshold(self) -> np.ndarray:
        """Get the thresholded data as an np.ndarray.

        Returns:
            np.ndarray: The thresholded data.
        """
        return np.array(self.raw_measurement_data["bins"]["threshold"])
``` 

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by GuillermoAbadLopez** [comment]
PR tackling this: https://github.com/qilimanjaro-tech/qililab/pull/718
